fasticker/urls.py
import settings
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fasticker.views.home', name='home'),
    # url(r'^fasticker/', include('fasticker.foo.urls')),
    url(r'^$', 'fasticker.core.views.index'),
    url(r'^items$', 'fasticker.core.views.items'),
    url(r'^recommendations$', 'fasticker.core.views.recommendations'),
    url(r'^board/(\d+)$', 'fasticker.core.views.board'),
    url(r'^item/(\d+)$', 'fasticker.core.views.item'),
    url(r'^item/(\d+)/edit$', 'fasticker.core.views.item_form'),
    url(r'^item/(\d+)/comment$', 'fasticker.core.views.item_comment_form'),
    url(r'^item/add$', 'fasticker.core.views.item_form'),
    url(r'^join$', 'fasticker.core.views.join'),
    url(r'^profile/(\d+)$', 'fasticker.core.views.profile'),

    url(r'^login$', 'django.contrib.auth.views.login',
        {"extra_context": {'next': '/'}}),
    url(r'^logout$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

fasticker/core/models.py
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models

from fasticker.core.middleware import register_admin
from fasticker.util import media_upload_to


@register_admin
class Color(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


@register_admin
class Context(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name


@register_admin
class Category(models.Model):
    name = models.CharField(max_length=30)
    parent = models.ForeignKey('self', null=True, blank=True)

    def __unicode__(self):
        if self.parent:
            return u'{} - {}'.format(self.parent, self.name)
        else:
            return self.name


@register_admin
class Preference(models.Model):
    category = models.ForeignKey(Category, null=True, blank=True)
    context = models.ForeignKey(Context, null=True, blank=True)
    color = models.ForeignKey(Color, null=True, blank=True)

    def __unicode__(self):
        return u' '.join(unicode(x) for x in (self.category, self.context, self.color) if x is not None)

    def clean(self):
        super(Preference, self).clean()
        if not any((self.category, self.context, self.color)):
            raise ValidationError('pick at least one condition')


@register_admin
class Item(models.Model):
    author = models.ForeignKey('Profile')
    name = models.CharField(max_length=60)
    memo = models.TextField(max_length=2000)
    image = models.ImageField(upload_to=media_upload_to)
    link = models.URLField(blank=True)

    category = models.ForeignKey(Category)
    context = models.ManyToManyField(Context, null=True, blank=True)
    color = models.ForeignKey(Color, null=True, blank=True)

    tags = models.CharField(max_length=80, blank=True)

    class Meta:
        ordering = ("-id",)

    def __unicode__(self):
        return self.name

    def get_tags(self):
        if self.tags:
            return (tag.strip() for tag in self.tags.split(','))
        else:
            return []


class Linkable(models.Model):
    LINK_ITEM = 'item'
    LINK_EXTERNAL_PAGE = 'external_page'
    LINK_YOUTUBE = 'youtube'

    LINK_CHOICES = (
        (LINK_ITEM, "Item"),
        (LINK_EXTERNAL_PAGE, "Extenal Page"),
        (LINK_YOUTUBE, "Youtube Video")
    )

    link = models.URLField(blank=True)
    link_type = models.CharField(max_length=12,
                                 choices=LINK_CHOICES,
                                 blank=True)

    class Meta:
        abstract = True


@register_admin
class ItemComment(Linkable):
    item = models.ForeignKey("Item")
    author = models.ForeignKey("Profile")
    memo = models.TextField(max_length=300)

    def __unicode__(self):
        return unicode(self.memo)


@register_admin
class Profile(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=20)
    photo = models.ImageField(upload_to=media_upload_to, blank=True)
    memo = models.TextField(max_length=100)
    following = models.ManyToManyField('self', blank=True)
    preferences = models.ManyToManyField(Preference, blank=True)

    def __unicode__(self):
        return unicode(self.user)


@register_admin
class Board(models.Model):
    name = models.CharField(max_length=60)
    author = models.ForeignKey(Profile)
    items = models.ManyToManyField(Item, through="ItemBoardContainsRelation")

    def __unicode__(self):
        return u"{} by {}".format(self.name, self.author)


@register_admin
class ItemBoardContainsRelation(models.Model):
    board = models.ForeignKey(Board)
    item = models.ForeignKey(Item)

    class Meta:
        ordering = ('pk',)

    def __unicode__(self):
        return u'{} - {}'.format(self.board.author, self.item)


def recommendations(preferences):
    for p in preferences:
        qs = Item.objects
        if p.category:
            qs = qs.filter(category=p.category)
        if p.color:
            qs = qs.filter(color=p.color)
        if p.context:
            qs = qs.filter(context=p.context)
        for item in qs:
            yield item

fasticker/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from fasticker.core import models


class ItemForm(forms.ModelForm):
    class Meta:
        model = models.Item
        fields = ("name", "memo", "image", "category", "context", "color", "link", "tags")

    def clean(self):
        cleaned_data = super(ItemForm, self).clean()
        if len(cleaned_data["context"]) == 0:
            cleaned_data["context"] = [context.id for context in models.Context.objects.all()]
        return cleaned_data


class ItemCommentForm(forms.ModelForm):
    class Meta:
        model = models.ItemComment
        fields = ("memo", )


class JoinForm(UserCreationForm):
    name = forms.CharField(label=_("Name"), max_length=30)
    username = forms.RegexField(label=_("Account"), max_length=30,
        regex=r'^[\w.@+-]+$',
        help_text=_("Letters, digits and @/./+/-/_ only."),
        error_messages={
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text=_("Enter the same password as above."))

    email = forms.EmailField(widget=forms.TextInput(attrs=dict({'class': 'required'},
                                                               maxlength=75)),
                             label=_("E-mail"))
    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
        return self.cleaned_data['email']

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(JoinForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
            models.Profile(user=user, name=self.cleaned_data["name"]).save()

        return user

    class Meta:
        fields = ("name", "email", "username",)
        model = User

fasticker/core/views.py
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from fasticker.core import models, forms
from fasticker.core.middleware import require_http_methods
from fasticker.util import autorotate, unique_everseen


@require_http_methods('GET')
def index(request):
    context = {}
    context["items"] = models.Item.objects.all()[:20]
    return render(request, 'index.html', context)


@require_http_methods('GET')
def items(request):
    category_id = request.GET.get("category_id", None)
    if category_id:
        c = models.Category.objects.get(id=category_id)
        ctx = dict(items=c.item_set.all())
    else:
        ctx = dict(items=models.Item.objects.all())

    color_id = request.GET.get("color_id", None)
    if color_id:
        ctx["items"] = ctx["items"].filter(color=color_id)

    context_id = request.GET.get("context_id", None)
    if context_id:
        ctx["items"] = ctx["items"].filter(context__in=context_id)
    ctx["categories"] = models.Category.objects.filter(parent=None)
    ctx["contexts"] = models.Context.objects.all()
    ctx["colors"] = models.Color.objects.all()

    return render(request, 'items.html', ctx)


@require_http_methods('GET')
def recommendations(request):
    profile = models.Profile.objects.get(id=1)
    preferences = profile.preferences.all()

    return render(request,
                  'recommendations.html',
                  dict(recommendations=unique_everseen(models.recommendations(preferences)),
                       preferences=preferences))


@require_http_methods('GET')
def board(request, board_id):
    ctx = dict(board=models.Board.objects.get(id=board_id))
    return render(request, 'board.html', ctx)


@require_http_methods('GET')
def board_form(request, board_id=None):
    ctx = dict(board=models.Board.objects.get(id=board_id))
    return render(request, 'board.html', ctx)


@require_http_methods('GET')
def item(request, item_id):
    ctx = dict(item=models.Item.objects.get(id=item_id))
    return render(request, 'item.html', ctx)


@login_required
@require_http_methods('POST')
def item_comment_form(request, item_id):
    form = forms.ItemCommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.item = models.Item.objects.get(id=item_id)
        comment.author = request.user.profile
        comment.save()
    else:
        print "fuck"
    return redirect(reverse('fasticker.core.views.item', args=(item_id, )))


@login_required
@require_http_methods('GET', 'POST')
def item_form(request, item_id=None):
    if item_id is not None:
        item = models.Item.objects.get(id=item_id)
    if request.method == 'POST':
        if item_id is None:
            form = forms.ItemForm(request.POST, request.FILES)
        else:
            form = forms.ItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            if item_id is None:
                item = form.save(commit=False)
                item.author = request.user.profile
                item.save()
                autorotate(item.image.file.name)
            else:
                form.save()

            return redirect('fasticker.core.views.items')
    else:
        if item_id is None:
            form = forms.ItemForm()
        else:
            form = forms.ItemForm(instance=item)

    ctx = {
        'form': form,
    }
    if item_id is not None:
        ctx["item_id"] = item_id
    return render(request, 'item_form.html', ctx)


@require_http_methods('GET', 'POST')
def join(request):
    if request.method == "POST":
        form = forms.JoinForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'registration/complete.html')
    else:
        form = forms.JoinForm()
    ctx = {"form": form}
    return render(request, 'registration/registration_form.html', ctx)


@require_http_methods('GET')
def profile(request, profile_id):
    profile = models.Profile.objects.get(id=profile_id)
    preferences = profile.preferences.all()
    context = dict(profile=profile,
                   recommendations=unique_everseen(models.recommendations(preferences)),
                   preferences=preferences,
                   boards=models.Board.objects.filter(author=profile_id))

    return render(request, 'profile.html', context)

fasticker/core/templates/base.html
{% with logged_in=user.is_authenticated %}
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <meta name="format-detection" content="telephone=no">

  <title>Fasticker</title>

  <!-- Included CSS Files -->
  <link rel="stylesheet" href="/static/app.css">
  <link rel="stylesheet" href="/static/chosen.css" />
  <script src="/static/modernizr.foundation.js"></script>

</head>

</head>
<body>
  <!-- Navigation -->
  <div class="row">
    <nav class="top-bar fixed">
      <ul>
        <li class="name"><h1><a href="/">FASTICKER</a></h1></li>
        <li class="toggle-topbar"><a href="#"></a></li>
      </ul>

      <section>
        <ul class="right">
          <li><a
            {% if logged_in %}
            href="{% url fasticker.core.views.item_form %}"
            {% else %}
            class="has-tip" data-width="200" title="로그인 후에 이용가능 합니다"
            {% endif %}
            >Make your Fashion</a>
          </li>
          {% if logged_in %}
          <li class="has-dropdown">
            <a href="#"><img src="{{ user.profile.photo.url }}">{{ user.profile.name }}</a>

            <ul class="dropdown">
              <li>
                <a href="{% url fasticker.core.views.profile user.profile.id %}">프로필</a>
              </li>
              <li><a href="{% url django.contrib.auth.views.logout %}">로그아웃</a></li>
            </ul>
          </li>
          {% else %}
          <li><a href="{% url fasticker.core.views.join %}">가입하기</a></li>
          <li><a href="{% url django.contrib.auth.views.login %}">로그인</a></li>
          {% endif %}
        </ul>
      </section>
    </nav>
  </div>

  <!--[if lt IE 8]>
  <div class="notification-bar">
    브라우저를 업그레이드해 주세요! <a href="http://browsehappy.com/">자세한 내용 보기</a>
  </div>
  <![endif]-->

  {% block content %}{% endblock %}

  <!-- Footer -->
  <footer class="row">
    <div class="twelve columns"><hr />
      <div class="row">

        <div class="six columns">
          <p>&copy; Copyright Fasticker.</p>
        </div>
        <!--
        <div class="six columns">
            <ul class="link-list right">
              <li><a href="#">Link 1</a></li>
              <li><a href="#">Link 2</a></li>
              <li><a href="#">Link 3</a></li>
              <li><a href="#">Link 4</a></li>
            </ul>
        </div>
      -->

    </div>
  </div>
</footer>
<!-- End Footer -->
<!-- Included JS Files -->
<!-- <script src="../public/assets/templates.js"></script>-->
<!-- Included JS Files (Compressed) -->
<script type="text/javascript" src="/static/jquery.js"></script>
<script type="text/javascript" src="/static/foundation.min.js"></script>

<!-- Initialize JS Plugins -->
<script  type="text/javascript" src="/static/app.js"></script>
<script type="text/javascript" src="/static/chosen.jquery.min.js"></script>
<script type="text/javascript" src="/static/jquery.masonry.min.js"></script>
<script type="text/javascript">
$(function(){
  $("select").chosen(); $(".chzn-select-deselect").chosen({allow_single_deselect:true});
  $(window).unload(function() {
    $('form input[type="submit"]').prop("disabled", false);
    $('form .spinner').hide();
  });


  $('form input[type="submit"]').click(function(e) {
    $('form .spinner').show();
       // workout
       setTimeout(function () {
        $('form input[type="submit"]').prop("disabled", true);
      }, 100);
     });

  var columns    = 5 ,
  setColumns = function() { columns = $( window ).width() > 767 ? 5 : 2; };
  setColumns();
  $( window ).resize( setColumns );

  var $container = $(".item-grid");

  $container.imagesLoaded( function(){
    $container.masonry({
      itemSelector : '.item',
      isAnimated: !Modernizr.csstransitions,
      columnWidth:  function( containerWidth ) { return containerWidth / columns; }

    });
  });

});
</script>
</body>
</html>
{% endwith %}

fasticker/core/templates/board.html
{% extends "base.html" %}
{% block content %}
<div class="row">
  <div class="twelve columns">
    <h4>{{ board.name }}</h4>
    <div class="row">
      <div class="eight columns">
        <h5>Items</h5>
        {% if board.items.exists %}
          <ul class="block-grid four-up mobile-two-up item-grid">
            {% for item in board.items.all %}
            <li class="item">
              <div class="th">
                <a href="{% url fasticker.core.views.item item.id %}"><img src="{{ item.image.url }}"></a>
              </div>
              <div>
                <a href="{% url fasticker.core.views.item item.id %}">{{ item.name }}</a>
              </div>
              {% if user.is_staff %}
              <div>
                {% if item.category %}<span class="tag">{{ item.category }}</span>{% endif %}
                {% if item.color %}<span class="tag">{{ item.color }}</span>{% endif %}
                {% for context in item.context.all %}
                <span class="tag">{{ context }}</span>
                {% endfor %}
              </div>
              {% endif %}
                <h6>
                  <a href="{% url fasticker.core.views.profile item.author.id %}">
                    <img src="{{ item.author.photo.url }}" style="width:24px" /> {{ item.author.name }}
                  </a>
                </h6>
              </a>
            </li>
            {% endfor %}
          </ul>
          {% else %}
          <div>아이템이 없습니다.</div>
          {% endif %}
      </div>
      <div class="four columns">
        <h4><img style="width: 24px" src="{{board.author.photo.url}}"> {{ board.author.name }}</h4>
        <p>{{ board.memo }}</p>
          <ul class="link-list">
            <li><a href="">Love</a></li>
            <li><a href="">Pin</a></li>
          </ul>
          <h5>4 Comments</h6>
          <div>
            <div><img src="http://placehold.it/24x24&text=[img]" /> Someone</div>
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit</p>
          </div>
          <div>
            <div><img src="http://placehold.it/24x24&text=[img]" /> Someone</div>
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit</p>
          </div>
          <div>
            <div><img src="http://placehold.it/24x24&text=[img]" /> Someone</div>
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit</p>
          </div>
          <div>
            <div><img src="http://placehold.it/24x24&text=[img]" /> Someone</div>
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit</p>
          </div>
          <div>
            <form action=""  method="POST">
              {% csrf_token %}
              <div>
                <input type="text" placeholder="댓글 내용" disabled="disabled" />
                <input type="submit" class="button small" value="댓글 쓰기" disabled="disabled" />
              </div>
            </form>
          </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

fasticker/core/templates/form.html
<form action="{{ action }}"  method="POST">
  <div style="display:none"><input type="hidden" name="next" value="{{ next }}" /></div>
  {% for field in form.hidden_fields %}
  {{ field }}
  {% endfor %}
  {% csrf_token %}

  {% if form.non_field_errors %}
  <div class="alert-box alert">
    {% for non_field_error in form.non_field_errors %}
    {{ non_field_error }}
    {% endfor %}
    <a href="#" class="close">&times;</a>
  </div>
  {% endif %}
  {% for field in form.visible_fields %}
  <div class="{% if field.errors %}error{% endif %}">
    <label for="{{ field.auto_id }}">{{ field.label }}</label>
    {{ field }}
    {% if field.errors %}
    {% for error in field.errors %}<small>{{error}}</small>{% endfor %}
    {% endif %}
  </div>
  {% endfor %}
  <div>
    <input type="submit" class="button small" value="{{ action_text }}" />
  </div>
</form>

fasticker/core/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="welcome">
  <h1>Fasticker</h1>
  <h5>당신의 마음을 붙여주세요.</h5>
</div>

<div class="row">
  <div class="two columns">
    <ul class="side-nav">
      <li><a href="{% url fasticker.core.views.recommendations %}">추천</a></li>
      <li><a href="{% url fasticker.core.views.items %}">아이템 찾기</a></li>
      <li class="divider"></li>
      <li>채팅</li>
      <li>친구 찾기</li>
    </ul>
  </div>

  <div class="ten columns">

    {% if items.exists %}
    <ul class="block-grid five-up mobile-two-up item-grid">
      {% for item in items %}
      <li class="item">
        <div class="th">
          <a href="{% url fasticker.core.views.item item.id %}"><img src="{{ item.image.url }}"></a>
        </div>
        <div>
          <a href="{% url fasticker.core.views.item item.id %}">{{ item.name }}</a>
        </div>
        <div>
          {% if item.category %}<span class="tag">{{ item.category }}</span>{% endif %}
          {% if item.color %}<span class="tag">{{ item.color }}</span>{% endif %}
          {% for context in item.context.all %}
          <span class="tag">{{ context }}</span>
          {% endfor %}
          {% for tag in item.get_tags %}
          <span class="tag">{{ tag }}</span>
          {% endfor %}
        </div>
        <h6>
          <a href="{% url fasticker.core.views.profile item.author.id %}">
            <img src="{{ item.author.photo.url }}" style="width:24px" /> {{ item.author.name }}
          </a>
        </h6>
      </a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <div>아이템이 없습니다.</div>
  {% endif %}

</div>
{% endblock %}

fasticker/core/templates/item.html
{% extends "base.html" %}
{% block content %}
<div class="row">
  <div class="twelve columns">
    <h4>{{ item.name }}</h4>
    <div class="row">
      <div class="eight columns">
        <img src="{{ item.image.url }}" />
      </div>
      <div class="four columns">
        <h4><img style="width: 24px" src="{{item.author.photo.url}}"> {{ item.author.name }}</h4>
        <p>{{ item.memo }}</p>
        <p>
          {% if item.link %}
            <a href="{{ item.link }}">구입처</a>
          {% else %}
            구입처 정보가 없습니다.
          {% endif %}
        </p>

        <h5>Tags</h5>
        <p>
          {% if user.is_staff %}
          {% if item.category %}<span class="tag">{{ item.category }}</span>{% endif %}
                {% if item.color %}<span class="tag">{{ item.color }}</span>{% endif %}
                {% for context in item.context.all %}
                <span class="tag">{{ context }}</span>
                {% endfor %}
          {% endif %}
          {% for tag in item.get_tags %}
            <span class="tag">{{ tag }}</span>
          {% endfor %}
        </p>

        <ul class="link-list">
          {% if item.author == user.profile %}
          <li><a href="{% url fasticker.core.views.item_form item.id %}">고치기</a></li>
          {% endif %}
        </ul>
        <h5>댓글 {{ item.itemcomment_set.count}} 개</h6>
        {% if item.itemcomment_set.exists %}
          {% for comment in item.itemcomment_set.all %}
          <div>
            <div><img style="width: 24px;" src="{{ comment.author.photo.url }}" /> {{ comment.author.name }}</div>
            <p>{{ comment.memo }}</p>
          </div>
          {% endfor %}
        {% else %}
        <div>댓글이 없습니다. 맨 처음으로 댓글을 달아주세요!</div>
        {% endif %}
        <div>
          <form action="{% url fasticker.core.views.item_comment_form item.id %}"  method="POST">
            {% csrf_token %}
            <input type="text" name="memo" placeholder="댓글 내용"
            {% if not logged_in %}
            disabled="disabled" class="has-tip" data-width="200" title="로그인 후에 이용가능 합니다"
            {% endif %}/>
            <input type="submit" class="button small" value="댓글 쓰기"
            {% if not logged_in %} disabled="disabled" {% endif %} />
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

fasticker/core/templates/item_form.html
{% extends "base.html" %}
{% block content %}

<div class="row">
  <div class="four columns centered panel">
    <h3>Make your Fashion</h3>
    <hr />
    <form action="" method="POST" enctype="multipart/form-data">
      <div style="display:none"><input type="hidden" name="next" value="{{ next }}" /></div>
      {% for field in form.hidden_fields %}
      {{ field }}
      {% endfor %}
      {% csrf_token %}

      {% if form.non_field_errors %}
      <div class="alert-box alert">
        {% for non_field_error in form.non_field_errors %}
        {{ non_field_error }}
        {% endfor %}
        <a href="#" class="close">&times;</a>
      </div>
      {% endif %}
      {% for field in form.visible_fields %}
      <div class="{% if field.errors %}error{% endif %}">
        <label for="{{ field.auto_id }}">{{ field.label }}
          {% if field.field.required %}<span class="label radius">필수</span>{% endif %}</label>
        {{ field }}
        {% if field.errors %}
        {% for error in field.errors %}<small>{{error}}</small>{% endfor %}
        {% endif %}
      </div>
      {% endfor %}
      <div>
        <input type="submit" class="button small" value="아이템 {% if item_id %}고치기{% else %}등록하기{% endif %}" />
        <img class="spinner" src="{{ STATIC_URL }}spinner.gif" style="height: 32px; display:none; "/>
      </div>
    </form>
  </div>
</div>
{% endblock %}

fasticker/core/templates/items.html
  {% extends "base.html" %}
  {% block content %}
  <div class="row">
    <div class="twelve columns">
      <h4>아이템 찾기</h4>
      <div class="row">
        <div class="two columns">
          <ul class="side-nav">
            <li><a href="{% url fasticker.core.views.items %}">전부 보기</a></li>
            <li class="divider"></li>
            <li class="header">분류</li>
            {% for category in categories %}
            <li><a href="{% url fasticker.core.views.items %}?category_id={{category.id}}">{{ category.name }}</a>
              {%include "items_nav_list.html" %}
            </li>
            {% endfor %}
            <li class="divider"></li>
            <li class="header">상황</li>
            {% for context in contexts %}
            <li><a href="{% url fasticker.core.views.items %}?context_id={{context.id}}">{{ context.name }}</a></li>
            {% endfor %}
            <li class="divider"></li>
            <li class="header">색상</li>
            {% for color in colors %}
            <li><a href="{% url fasticker.core.views.items %}?color_id={{color.id}}">{{ color.name }}</a></li>
            {% endfor %}
          </ul>
        </div>

        <div class="ten columns main-column">
          {% if items.exists %}
          <ul class="block-grid five-up mobile-two-up item-grid">
            {% for item in items %}
            <li class="item">
              <div class="th">
                <a href="{% url fasticker.core.views.item item.id %}"><img src="{{ item.image.url }}"></a>
              </div>
              <div>
                <a href="{% url fasticker.core.views.item item.id %}">{{ item.name }}</a>
              </div>
              <div>
                {% if item.category %}<span class="tag">{{ item.category }}</span>{% endif %}
                {% if item.color %}<span class="tag">{{ item.color }}</span>{% endif %}
                {% for context in item.context.all %}
                <span class="tag">{{ context }}</span>
                {% endfor %}
                {% for tag in item.get_tags %}
                <span class="tag">{{ tag }}</span>
                {% endfor %}
              </div>
                <h6>
                  <a href="{% url fasticker.core.views.profile item.author.id %}">
                    <img src="{{ item.author.photo.url }}" style="width:24px" /> {{ item.author.name }}
                  </a>
                </h6>
              </a>
            </li>
            {% endfor %}
          </ul>
          {% else %}
          <div>아이템이 없습니다.</div>
          {% endif %}

        </div>
      </div>
    </div>
  </div>
  {% endblock %}

fasticker/core/templates/items_nav_list.html
{%if category.category_set.exists %}
    <ul>
     {%for child in category.category_set.all %}
        <li><a href="{% url fasticker.core.views.items %}?category_id={{child.id}}">{{ child.name }}</a></li>
          {%with category=child template_name="items_nav_list.html" %}
               {%include template_name%}
          {%endwith%}
     {%endfor%}
     </ul>
{%endif%}